default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_development
  username: postgres
  password: 0047196

test:
  <<: *default
  database: blog_development
  username: postgres
  password: 0047196

production:
  <<: *default
  database: blog_production
